#define ID_MAINDLG                     101
#define ID_CLASSNAME                   1000
#define ID_HANDLE                      1001
#define ID_WNDPROC                     1002
#define ID_HOOK                        1004
#define ID_EXIT                        1005
#define ID_STATIC                      -1
#define DS_MODALFRAME                   0x80
#define WS_POPUP                        0x80000000
#define WS_CAPTION                      0xC00000
#define WS_SYSMENU                      0x80000
#define ES_AUTOHSCROLL                  0x80
#define ES_READONLY                     0x800